import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { EmblaCarousel } from "../components/Carousel";

export default function Home() {
  return (
    <div>
      <Head>
        <title>F1 Calendar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="grid gap-4 md:gap-0 md:grid-cols-2">
          <div>
            <EmblaCarousel></EmblaCarousel>
          </div>
          <div className="bg-green-300">HELLO</div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
