import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { EmblaCarousel } from "../components/Carousel";
import RaceSchedule from "../components/RaceSchedule";
import PartialStandings from "../components/PartialStandings";
import { Button } from "@nextui-org/react";
import Footer from "../components/Footer";

const currentYear = new Date().getFullYear();

export const getStaticProps = async () => {
  const res = await fetch(`https://ergast.com/api/f1/current.json`);
  const schedule = await res.json();
  const res2 = await fetch(`https://ergast.com/api/f1/current/next.json`);
  const nextRace = await res2.json();
  const res3 = await fetch(
    "https://ergast.com/api/f1/current/driverStandings.json"
  );
  const driverStandings = await res3.json();
  const res4 = await fetch(
    "https://ergast.com/api/f1/current/constructorStandings.json"
  );
  const constructorStandings = await res4.json();

  return {
    props: {
      calendarData: schedule.MRData,
      nextRace: nextRace.MRData.RaceTable.round,
      driverStandings: driverStandings,
      constructorStandings: constructorStandings,
    },
  };
};

export default function Home({
  calendarData,
  nextRace,
  driverStandings,
  constructorStandings,
}) {
  const [raceId, setRaceId] = useState(Number(nextRace) - 1);
  return (
    <div>
      <Head>
        <title>F1 Calendar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* SCHEDULE */}
        <div className="schedule-container bg-[#e6e5e5]">
          <h1 className="text-center text-3xl font-['Raleway'] mb-4 lg:text-4xl bg-[#42636e] text-white py-1 font-extralight tracking-wide">
            F1 Schedule {currentYear}
          </h1>
          <div className="grid  gap-4 md:gap-0 md:grid-cols-[1.3fr_1fr] md:border-b  md:rounded-lg md:pt-2 md:pb-6">
            <div className="pt-10 ">
              <EmblaCarousel
                raceId={raceId}
                setRaceId={setRaceId}
              ></EmblaCarousel>
            </div>
            <div className="py-10">
              <RaceSchedule data={calendarData} raceId={raceId}></RaceSchedule>
            </div>
          </div>
        </div>

        {/* STANDINGS */}
        <div className="grid md:grid-cols-2   md:rounded-lg ">
          <div className="block">
            <Image
              src={"/img/home/ferrari-pit.jpg"}
              width={1200}
              height={800}
              layout="responsive"
              alt="Pit stop Ferrari"
            ></Image>
          </div>
          <div className="grid grid-rows-[0.1fr_400px_0.2fr] md:grid-rows-[0.1fr_1fr_0.2fr] pt-6 md:pt-0 border-b">
            <h1 className="text-center text-2xl pt-1 font-mono">
              Driver Standings
            </h1>
            <div className="overflow-y-scroll wrapper">
              <PartialStandings
                standings={driverStandings}
                type="Driver"
              ></PartialStandings>
            </div>
            <Button bordered auto className="w-1/4 m-auto my-2">
              <a href={"/driver-standings"}>Full Driver Standings</a>
            </Button>
          </div>
          <div className="grid grid-rows-[0.1fr_400px_0.2fr] md:grid-rows-[0.1fr_1fr_0.2fr]  pt-6 md:pt-0">
            <h1 className="text-center text-2xl pt-1 font-mono ">
              Constructor Standings
            </h1>
            <div className="overflow-y-scroll wrapper">
              <PartialStandings
                standings={constructorStandings}
                type="Constructor"
              ></PartialStandings>
            </div>
            <Button bordered auto className="w-1/4 m-auto mb-2 ">
              <a href={"/driver-standings"}>Full Constructor Standings</a>
            </Button>
          </div>
          <div className="block">
            <Image
              src={"/img/home/finish-line.jpg"}
              width={1200}
              height={800}
              layout="responsive"
              alt="Finish Line"
            ></Image>
          </div>
        </div>
        <div className="font-['Raleway'] bg-[#f1f3f5]  ">
          <h1 className="p-4 md:p-5 text-lg md:text-2xl tracking-wider text-center ">
            “I’ve always believed that you should never, ever give up and you
            should always <span className="text-red-600">keep fighting</span>{" "}
            even when there’s only a slightest chance.” –{" "}
            <span className="text-red-600">Michael</span> Schumacher
          </h1>
        </div>
      </main>
    </div>
  );
}
